name: build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: go mod init redis-go-to-master && go build -ldflags="-s -w" -o redis-go-to-master .
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: redis-go-to-master
